# Generated by Django 5.0.3 on 2024-11-29 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Musicas', '0006_delete_usuarios'),
        ('Usuarios', '0002_alter_usuarios_options_usuarios_atualizado_em_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='User',
        ),
    ]
