# Generated by Django 5.0.3 on 2024-08-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('artista', models.CharField(max_length=200)),
                ('album', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=200)),
                ('url_reproducao', models.CharField(max_length=200)),
            ],
        ),
    ]
