# Generated by Django 5.0.3 on 2024-08-30 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musicas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.CharField(max_length=10)),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='musicas',
            name='album',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='musicas',
            name='artista',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='musicas',
            name='genero',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='musicas',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='musicas',
            name='url_reproducao',
            field=models.CharField(max_length=100),
        ),
    ]
