# Generated by Django 5.0.3 on 2024-11-22 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musicas', '0003_usuarios_comentario_playlist_playlist_usuario_albuns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albuns',
            name='musicas',
        ),
        migrations.RemoveField(
            model_name='musicas',
            name='album',
        ),
        migrations.AddField(
            model_name='musicas',
            name='albuns',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Musicas.albuns'),
            preserve_default=False,
        ),
    ]
