# Generated by Django 5.0.3 on 2024-11-22 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Musicas', '0005_musicasalbuns'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
