# Generated by Django 5.1.3 on 2024-11-29 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Musicas', '0006_delete_usuarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='playlist',
        ),
        migrations.AddField(
            model_name='comentario',
            name='albuns',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Musicas.albuns'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='nota',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
    ]
