# Generated by Django 4.2.16 on 2024-12-02 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_rename_usuarios_user'),
        ('Musicas', '0007_remove_comentario_playlist_comentario_albuns_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicasPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='musicas',
            name='albuns',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musicas', to='Musicas.albuns'),
        ),
        migrations.AlterField(
            model_name='musicas',
            name='url_reproducao',
            field=models.URLField(),
        ),
        migrations.RenameModel(
            old_name='Albuns',
            new_name='Playlist',
        ),
        migrations.DeleteModel(
            name='MusicasAlbuns',
        ),
        migrations.AddField(
            model_name='musicasplaylist',
            name='musicas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Musicas.musicas'),
        ),
        migrations.AddField(
            model_name='musicasplaylist',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Musicas.playlist'),
        ),
    ]
