# Generated by Django 4.2.16 on 2024-12-02 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Musicas', '0008_musicasplaylist_comentario_usuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='albuns',
            new_name='playlist',
        ),
        migrations.RenameField(
            model_name='musicas',
            old_name='albuns',
            new_name='playlist',
        ),
    ]
