# Generated by Django 4.2.16 on 2024-12-02 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Musicas', '0012_rename_user_comentario_usuarios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
